Added diff option to compare processed profiles.
lpw25/prof_alloc pull request #22
Opened 2018-08-01 13:13 UTC by nandor

`prof_spacetime diff profile_1 profile2` compares the number of memory blocks live at program exit time in each file in an application, producing an output along the lines of:

```
File                                                    Words    Allocations         Blocks
src/utils.ml                                          -753885        -765543        -225188
src/stdune/path.ml                                    -323112      -13199839        -107428
src/stdune/map.ml                                       +2496           -762           +836
string.ml                                             +139383        +325271         +21483
pervasives.ml                                         +449678       +1514358         -40923
```

2018-09-20 15:43 UTC, lpw25 commented
Sorry for the slow response. I've found time to review this now. 

I'm a little unsure about defaulting to splitting things by file. None of the other commands work in terms of files. I assume that you did this because you wanted to compare two different implementations of a file, and so the individual allocations did not have the same location in the two profiles. I can't think of a simple better approach, so I guess its fine for now.

2018-09-20 15:50 UTC, nandor commented
I defaulted to file-level granularity as the line numbers of allocation points are bound to change between two different versions and the comparisons would be quite useless. File names closely match modules and I found them to be quite useful.

2018-09-20 15:55 UTC, lpw25 requested changes
A bit of style nitpicking, and the `-p` option should be respected. Once that's addressed its good to go.

2018-09-20 15:55 UTC, lpw25 commented on bin/prof_spacetime.ml
> +  | Diff of
This command should be able to run on either processed or unprocessed profiles, based on the `-p` option, just like the other commands. So I would expect to see a `processed` field here like in the other cases.

2018-09-20 15:55 UTC, lpw25 commented on src/diff.ml
> +
Please no blank lines within expressions

2018-09-20 15:55 UTC, lpw25 commented on src/diff.ml
> +        acc |> AllocMap.update name (fun v -> Some (match v with
I'd prefer to avoid using `|>` in general and especially for just passing an argument like this.

2018-09-20 15:55 UTC, lpw25 commented on src/diff.ml
> +  in loop snapshot AllocMap.empty
House style: `in` on its own line unless it is on the same line as `let`.

2018-09-20 15:55 UTC, lpw25 commented on src/diff.ml
> +  let diffs = NameSet.elements keys
There needs to be a newline after `diffs =` otherwise it is awkward to read.

2018-09-20 15:56 UTC, lpw25 commented
> I defaulted to file-level granularity as the line numbers of allocation points are bound to change between two different versions and the comparisons would be quite useless. File names closely match modules and I found them to be quite useful.

Yeah, that's what I figured. I think function-level granularity would fit better with the rest of the tool, and it should be possible, but it is much harder to implement so I think file-level is fine for now.

2018-09-20 16:19 UTC, nandor commented
Do the spacetime profiles capture function information though? I haven't found any methods to retrieve function names. 

I have addressed your style comments.

2018-09-20 22:38 UTC, lpw25 commented
> Do the spacetime profiles capture function information though?

Yes and no. IIRC we have the address of the call site, and the dwarf info can give you the symbol of the function containing that address. So we could get it if we wanted to as long as the user used the `-e` option. It would be a reasonable amount of work though. Not worth it for this simple PR -- just thinking out loud about how we might do things in an ideal world.

2018-09-20 22:42 UTC, lpw25 commented
>  It would be a reasonable amount of work though.

Actually, I'd forgotten that this is already implemented in spacetime_lib. It's not exposed well in the model in this repo -- it only appears as part of the location string -- but it wouldn't be hard to expose it properly.

2018-10-01 10:36 UTC, lpw25 commented
All looks good.

2018-10-01 10:36 UTC, merged